<?php
//SITE CONFIG
$SITE_NAME = ''; //INSERT YOUR SITE NAME
$SITE_DOMAIN = ''; //INSERT SITE DOMAIN, FOR EXAMPLE google.com


//MYSQL CONFIG
$DATABASE_HOST = 'localhost';
$DATABASE_USER = ''; //INSERT DB USER HERE
$DATABASE_PASS = ''; //INSERT DB PASSWORD HERE
$DATABASE_NAME = ''; //INSERT DB NAME HERE


//SMTP CONFIG
$SMTP_HOST = ''; //INSERT SMTP HOST HERE
$SMTP_AUTH = true; //ENABLE SMTP AUTHENTICATION
$SMTP_USERNAME = ''; //INSERT SMTP USER NAME HERE
$SMTP_PASSWORD = ''; //INSERT SMTP PASSWORD HERE
$SMTP_ENCRYPTION = 'ssl'; //SET SMTP ENCRYPTION MODE
$SMTP_PORT = 465; //SET SMTP PORT
?>
